### PR TITLE
 Switch to v3 API to fix #24 

### LINKED ISSUE #24: Subscription not working
It doesn't return an error, but when debugging the code I find that the call to the API returns this:

HTTP/1.0 302 Moved Temporarily\r\n
Server: AkamaiGHost\r\n
Content-Length: 0\r\n
Location: https://us19.api.mailchimp.com/1.3/?output=php&method=listSubscribe\r\n
Date: Wed, 08 Aug 2018 15:00:04 GMT\r\n
Connection: close\r\n
\r\n

any idea what's happening?

### PR DESCRIPTION
**Pull request by mariavilaro**
I changed the readme because I noticed that the merge fields are not saved if not in UPPERCASE

### CODE REVIEW

**Comment by LukeTowers** [comment]
Awesome, thanks @mariavilaro! Could you bump the version and provide a changelog entry in version.yaml for the marketplace as well?

**Comment by mariavilaro** [comment]
Done!

**Comment by LukeTowers** [comment]
@mariavilaro awesome! So does it all work perfectly now?

**Comment by mariavilaro** [comment]
Now it does, sorry, I didn't test it without merge fields in the form

**Comment by LukeTowers** [comment]
Thanks!

**Pull request merged**
